version: '3.7'

services:
  athlete_data_input_database:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
     - athlete_data_input_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGTZ=${PGTZ}
    ports:
      - 5432:5432
    restart: always

  # comment out for develope mode (when developing, the database is needed.)
  #athlete_data_input_backend:
  #  build:
  #    context: ./backend
  #    dockerfile: Dockerfile
  #  ports:
  #    - 1324:1323
  #  restart: always

volumes:
  athlete_data_input_db_data:
